sys = [['verum_'],
['verum_', 'poss_'],
['not_nec_', 'nec_', 'falsum_', 'verum_'],
['cont_', 'falsum_', 'verum_'],
['not_cont_fal', 'verum_'],
['id_', 'verum_'],
['falsum_', 'id_', 'imp_or_cont_tr', 'verum_'],
['falsum_', 'cont_tr', 'verum_'],
['not_cont_tr', 'not_cont_fal', 'verum_'],
['id_', 'nec_or_cont_fal', 'verum_'],
['id_', 'falsum_', 'verum_', 'neg_'],
['cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['rigid_', 'verum_'],
['nec_', 'verum_'],
['imposs_', 'falsum_', 'verum_', 'poss_'],
['falsum_', 'verum_'],
['nec_', 'not_nec_', 'imposs_', 'falsum_', 'verum_', 'poss_'],
['cont_', 'falsum_', 'verum_', 'poss_'],
['not_cont_fal', 'verum_', 'poss_'],
['id_', 'verum_', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'falsum_', 'verum_', 'poss_'],
['cont_', 'falsum_', 'cont_tr', 'verum_', 'poss_'],
['not_cont_tr', 'not_cont_fal', 'verum_', 'poss_'],
['id_', 'nec_or_cont_fal', 'verum_', 'poss_'],
['nec_', 'id_', 'neg_', 'not_nec_', 'imposs_', 'falsum_', 'verum_', 'poss_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'poss_'],
['rigid_', 'verum_', 'poss_'],
['nec_', 'verum_', 'poss_'],
['falsum_', 'verum_', 'poss_'],
['nec_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['nec_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal'],
['nec_', 'id_', 'not_nec_', 'falsum_', 'verum_'],
['nec_', 'not_nec_', 'falsum_', 'cont_tr', 'verum_'],
['nec_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'not_nec_', 'falsum_', 'verum_', 'nec_or_cont_fal'],
['nec_', 'not_nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['cont_', 'not_cont_fal', 'falsum_', 'verum_'],
['cont_', 'id_', 'falsum_', 'verum_'],
['id_', 'imp_or_cont_tr', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['cont_', 'falsum_', 'cont_tr', 'verum_'],
['cont_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['id_', 'cont_', 'falsum_', 'verum_', 'nec_or_cont_fal'],
['id_', 'neg_', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_'],
['rigid_', 'cont_', 'falsum_', 'verum_'],
['cont_', 'nec_', 'falsum_', 'verum_'],
['imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['not_cont_fal', 'id_', 'verum_'],
['id_', 'imp_or_cont_tr', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal'],
['not_cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['id_', 'verum_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['cont_fal', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['rigid_', 'not_cont_fal', 'verum_'],
['rigid_', 'not_cont_fal', 'verum_', 'nec_'],
['imposs_', 'falsum_', 'verum_', 'not_cont_fal', 'poss_'],
['not_cont_fal', 'falsum_', 'verum_'],
['id_', 'falsum_', 'cont_tr', 'verum_'],
['not_cont_tr', 'not_cont_fal', 'id_', 'verum_'],
['id_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['rigid_', 'id_', 'verum_'],
['nec_', 'id_', 'verum_'],
['id_', 'imposs_', 'falsum_', 'verum_', 'poss_'],
['id_', 'falsum_', 'verum_'],
['id_', 'imp_or_cont_tr', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'imp_or_cont_tr', 'falsum_', 'verum_', 'nec_or_cont_fal'],
['id_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'nec_or_cont_fal'],
['rigid_', 'falsum_', 'cont_tr', 'verum_'],
['nec_', 'falsum_', 'cont_tr', 'verum_'],
['imposs_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['rigid_', 'not_cont_tr', 'not_cont_fal', 'verum_'],
['nec_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['imposs_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['not_cont_tr', 'not_cont_fal', 'falsum_', 'verum_'],
['rigid_', 'id_', 'nec_or_cont_fal', 'verum_'],
['nec_', 'id_', 'nec_or_cont_fal', 'verum_'],
['id_', 'imposs_', 'falsum_', 'verum_', 'nec_or_cont_fal', 'poss_'],
['id_', 'falsum_', 'nec_or_cont_fal', 'verum_'],
['cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['rigid_', 'falsum_', 'verum_', 'cont_'],
['not_cont_tr', 'rigid_', 'not_cont_fal', 'verum_'],
['rigid_', 'nec_', 'verum_'],
['rigid_', 'falsum_', 'verum_'],
['rigid_', 'nec_', 'not_cont_fal', 'verum_'],
['nec_', 'falsum_', 'verum_'],
['id_', 'falsum_', 'verum_', 'imp_or_cont_tr'],
['poss_'],
['not_nec_', 'nec_', 'imposs_', 'poss_'],
['cont_', 'falsum_', 'poss_'],
['id_', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'poss_'],
['cont_', 'falsum_', 'cont_tr', 'poss_'],
['verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'nec_or_cont_fal', 'poss_'],
['nec_', 'id_', 'neg_', 'not_nec_', 'imposs_', 'poss_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'poss_'],
['nec_', 'poss_'],
['imposs_', 'poss_'],
['falsum_', 'poss_'],
['nec_', 'not_nec_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['nec_', 'not_nec_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'poss_'],
['nec_', 'not_nec_', 'imposs_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['nec_', 'not_nec_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'nec_or_cont_fal', 'poss_'],
['nec_', 'not_nec_', 'imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['cont_', 'falsum_', 'verum_', 'not_cont_fal', 'poss_'],
['cont_', 'id_', 'falsum_', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['cont_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'cont_', 'falsum_', 'nec_or_cont_fal', 'poss_'],
['nec_', 'id_', 'neg_', 'not_nec_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['cont_', 'nec_', 'falsum_', 'poss_'],
['not_cont_fal', 'id_', 'verum_', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'poss_'],
['cont_', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'poss_'],
['id_', 'verum_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr', 'poss_'],
['nec_', 'id_', 'neg_', 'not_nec_', 'imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['rigid_', 'not_cont_fal', 'verum_', 'poss_'],
['nec_', 'verum_', 'rigid_', 'not_cont_fal', 'poss_'],
['not_cont_fal', 'falsum_', 'verum_', 'poss_'],
['id_', 'cont_', 'falsum_', 'cont_tr', 'poss_'],
['id_', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'poss_'],
['rigid_', 'id_', 'verum_', 'poss_'],
['nec_', 'id_', 'poss_'],
['id_', 'imposs_', 'poss_'],
['id_', 'falsum_', 'poss_'],
['nec_', 'id_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['nec_', 'id_', 'neg_', 'not_nec_', 'imposs_', 'imp_or_cont_tr', 'nec_or_cont_fal', 'poss_'],
['id_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'nec_or_cont_fal', 'poss_'],
['cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['nec_', 'cont_', 'falsum_', 'cont_tr', 'poss_'],
['verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['nec_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'verum_', 'rigid_', 'nec_or_cont_fal', 'poss_'],
['nec_', 'id_', 'nec_or_cont_fal', 'poss_'],
['id_', 'imposs_', 'nec_or_cont_fal', 'poss_'],
['id_', 'falsum_', 'nec_or_cont_fal', 'poss_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['nec_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'poss_'],
['rigid_', 'nec_', 'verum_', 'poss_'],
['rigid_', 'falsum_', 'verum_', 'poss_'],
['nec_', 'falsum_', 'poss_'],
['not_nec_', 'nec_'],
['not_nec_', 'nec_', 'id_'],
['not_nec_', 'nec_', 'id_', 'nec_or_cont_fal'],
['nec_', 'id_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['nec_', 'not_nec_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'id_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['nec_', 'not_nec_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'id_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal'],
['nec_', 'not_nec_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal'],
['nec_', 'id_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['nec_', 'not_nec_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'not_nec_', 'falsum_', 'cont_tr', 'verum_'],
['nec_', 'id_', 'not_nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'not_nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_'],
['nec_', 'id_', 'not_nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'nec_or_cont_fal'],
['cont_', 'falsum_'],
['cont_', 'id_', 'falsum_'],
['cont_', 'falsum_', 'cont_tr'],
['cont_', 'id_', 'falsum_', 'nec_or_cont_fal'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr'],
['cont_', 'nec_', 'falsum_'],
['id_', 'cont_', 'falsum_', 'verum_', 'not_cont_fal'],
['id_', 'imp_or_cont_tr', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal'],
['cont_', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal'],
['id_', 'cont_', 'falsum_', 'verum_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal'],
['nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal'],
['imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'poss_'],
['cont_', 'id_', 'falsum_', 'cont_tr'],
['id_', 'cont_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['id_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr'],
['id_', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['cont_', 'nec_', 'id_', 'falsum_'],
['id_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'poss_'],
['id_', 'imp_or_cont_tr', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'imp_or_cont_tr', 'cont_', 'falsum_', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['id_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'nec_or_cont_fal'],
['cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['cont_', 'nec_', 'falsum_', 'cont_tr'],
['cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['nec_', 'id_', 'cont_', 'falsum_', 'nec_or_cont_fal'],
['id_', 'imposs_', 'cont_', 'falsum_', 'verum_', 'rigid_', 'nec_or_cont_fal', 'poss_'],
['cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr'],
['nec_', 'cont_', 'falsum_', 'verum_', 'rigid_'],
['not_cont_fal'],
['not_cont_fal', 'id_'],
['not_cont_fal', 'id_', 'imp_or_cont_tr', 'cont_tr'],
['not_cont_fal', 'cont_tr'],
['not_cont_fal', 'not_cont_tr'],
['not_cont_fal', 'id_', 'nec_or_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'cont_fal', 'cont_tr', 'not_cont_fal', 'not_cont_tr'],
['cont_fal', 'not_cont_fal', 'cont_tr', 'not_cont_tr'],
['not_cont_fal', 'id_', 'cont_tr'],
['not_cont_fal', 'id_', 'not_cont_tr'],
['id_', 'cont_fal', 'cont_tr', 'not_cont_fal', 'not_cont_tr'],
['rigid_', 'not_cont_fal', 'id_', 'verum_'],
['nec_', 'id_', 'verum_', 'rigid_', 'not_cont_fal'],
['id_', 'imposs_', 'falsum_', 'verum_', 'not_cont_fal', 'poss_'],
['not_cont_fal', 'id_', 'falsum_', 'verum_'],
['id_', 'imp_or_cont_tr', 'cont_fal', 'cont_tr', 'not_cont_fal', 'not_cont_tr'],
['id_', 'neg_', 'imp_or_cont_tr', 'cont_fal', 'cont_tr', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['id_', 'cont_fal', 'cont_tr', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal'],
['nec_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal'],
['imposs_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'poss_'],
['not_cont_fal', 'not_cont_tr', 'verum_'],
['rigid_', 'not_cont_fal', 'not_cont_tr', 'verum_'],
['not_cont_fal', 'falsum_', 'not_cont_tr', 'verum_'],
['id_', 'verum_', 'rigid_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'verum_', 'rigid_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['id_', 'imposs_', 'falsum_', 'verum_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'falsum_', 'verum_', 'not_cont_fal', 'nec_or_cont_fal', 'not_cont_tr'],
['cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['rigid_', 'not_cont_fal', 'falsum_', 'verum_'],
['nec_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal'],
['id_'],
['id_', 'imp_or_cont_tr'],
['id_', 'cont_tr'],
['id_', 'nec_or_cont_fal'],
['id_', 'neg_'],
['cont_fal', 'id_', 'cont_tr'],
['nec_', 'id_'],
['id_', 'falsum_'],
['id_', 'imp_or_cont_tr', 'nec_or_cont_fal', 'neg_'],
['cont_fal', 'id_', 'cont_tr', 'nec_or_cont_fal'],
['id_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'id_', 'falsum_', 'cont_tr'],
['id_', 'imposs_', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['id_', 'falsum_', 'cont_tr'],
['not_cont_fal', 'id_', 'not_cont_tr', 'verum_'],
['id_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['id_', 'imposs_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr', 'poss_'],
['id_', 'falsum_', 'verum_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'nec_or_cont_fal'],
['id_', 'falsum_', 'nec_or_cont_fal'],
['id_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['nec_', 'id_', 'cont_fal', 'falsum_', 'cont_tr'],
['id_', 'imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'poss_'],
['cont_fal', 'id_', 'falsum_', 'cont_tr'],
['rigid_', 'nec_', 'id_', 'verum_'],
['rigid_', 'id_', 'falsum_', 'verum_'],
['nec_', 'id_', 'falsum_'],
['cont_tr'],
['cont_fal', 'cont_tr'],
['nec_', 'falsum_', 'cont_tr'],
['falsum_', 'cont_tr'],
['id_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['nec_', 'id_', 'cont_fal', 'falsum_', 'cont_tr', 'nec_or_cont_fal'],
['id_', 'imposs_', 'cont_fal', 'cont_', 'falsum_', 'cont_tr', 'verum_', 'rigid_', 'nec_or_cont_fal', 'poss_'],
['id_', 'cont_fal', 'falsum_', 'cont_tr', 'nec_or_cont_fal'],
['cont_fal', 'nec_', 'falsum_', 'cont_tr'],
['cont_fal', 'falsum_', 'cont_tr'],
['nec_', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['not_cont_fal', 'poss_', 'not_cont_tr', 'verum_'],
['falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'falsum_', 'verum_', 'rigid_', 'not_cont_fal', 'not_cont_tr'],
['nec_', 'id_', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['id_', 'falsum_', 'verum_', 'rigid_', 'nec_or_cont_fal'],
['nec_', 'id_', 'falsum_', 'nec_or_cont_fal'],
['nec_', 'cont_fal', 'falsum_', 'cont_tr', 'verum_', 'rigid_'],
['rigid_', 'nec_', 'falsum_', 'verum_'],
['nec_'],
['nec_', 'falsum_'],
['falsum_']
]

